spring:
  datasource:
    url: jdbc:tc:postgresql:14:///
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true

logging:
  level:
    org.springframework.data.querydsl.binding: DEBUG