spring:
  datasource:
    hikari:
      connection-timeout: 2000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
  content:
    storage:
      type:
        default: fs

logging:
  level:
    org.springframework.data.querydsl.binding: DEBUG

contentgrid:
  audit:
    messaging:
      source: https://example.contentgrid.cloud/abc
      destination: audit
  thunx:
    abac:
      source: none
