spring:
  main:
    web-application-type: none
  data:
    jpa:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
      - com.contentgrid.thunx.api.autoconfigure.AbacAutoConfiguration
