server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:tc:postgresql:14:///
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
  data:
    jpa:      
      repositories:
        bootstrap-mode: DEFERRED